### ISSUE TITLE
Delete this repo X(

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#10]
#### What do you want to talk about?
Apparently when you generate a repo from a template github has a permanent association with the template -- we don't want that, I was just lazily copying all of the node boilerplate.  This has nothing to do with the appliance template.

We'll lose our issue history, but we can keep everything else.  Lets do this after the PRs are merged.

#### Relevant Resources / Research
No.

**Comment by Laurian** [comment]
what if you delete `tvkitchen/appliance-template`?

**Comment by slifty** [comment]
... that's actually a really good question laurian -- I'll try that first.

**Comment by Laurian** [comment]
backup things first :P

**Comment by slifty** [comment]
TOO LATE DOING IT LIVE

(jk I have local copies of everything)

**Comment by slifty** [comment]
OMG THAT WORKED!

We no longer have to delete everything!
