### ISSUE TITLE
Replace STREAM.DATA

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#14]
#### Description
The ingestion engine is going to write to a kafka queue which we had originally called `STREAM.DATA`.  This is a little generic, and maybe we should call it `STREAM.MPEGTS` MPEGTS instead.

If so, lets do this before we publish, that way we can remove the (uselessly) generic `STREAM.DATA`.

#### Relevant Resources / Research
None

#### Related Issues
None

**Comment by reefdog** [comment]
I do think something more descriptive than `DATA` is good, now that we have a better understanding of the data pipeline. However, I think `MPEGTS` is too specific and would recommend going with `CONTAINER` (or `PACKAGE`, though I think that's overloaded and too similar to `PACKET`) and simply documenting our MPEGTS usage.

**Comment by slifty** [comment]
Good thought; another possibility: `CHUNK`

**Comment by reefdog** [comment]
We _could_ conceivably have format-specific suffixes, e.g. `STREAM.CONTAINER.MPEGTS` or `STREAM.VIDEO.H264` if we actually think there will be appliance or pipeline components that truly want to distinguish between encodings; _but_ I think this is wrong until we're convinced why it's right.

**Comment by slifty** [comment]
I do like the look of that, but that also introduces another level of nesting that we aren't supporting yet.

I think `STREAM.CONTAINER` with clear documentation that it will exclusively be mpegts for now is appropriate.  Even if we add another container format someday we can do so in a way that still respects that rule for `STREAM.CONTAINER`

**Comment by reefdog** [comment]
Cool. Wanna make it so and I can review/merge before the publish?
