### ISSUE TITLE
"package:" labels

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#15]
#### What do you want to talk about?
Since this is a monorepo we should probably make labels for each package so when issues are created we can more easily organize them... Right?

I'd suggest a label prefix of `package:` for these.

#### Relevant Resources / Research
There's probably a good resource out there for monorepo github labels...

**Comment by reefdog** [comment]
I'm good with that!

**Comment by reefdog** [comment]
Went ahead and implemented.
