### ISSUE TITLE
Fix broken links and misinformation in CONTRIBUTING

### ISSUE THREAD

**Issue by reefdog** [tvkitchen/base#24]
#### Description
Our [CONTRIBUTING.md](https://github.com/tvkitchen/base/blob/master/docs/CONTRIBUTING.md) contains a few broken links (e.g. to our code of conduct in the first graf) and some misinformation (e.g., we aren't using Sequelize). We should do a cleanup pass.

**Comment by sahilister** [comment]
hey @reefdog i can do the links, if okay assign me this.

**Comment by slifty** [comment]
@sahilister that would be great thank you!
