### ISSUE TITLE
Make better package descriptions

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#28]
#### Description
Now that [our packages are published](https://www.npmjs.com/org/tvkitchen) (yay!!!) our descriptions are clearly awkward.

We shouldn't say "This package exports" in all of them, for instance.

What about:

```
@tvkitchen/base-classes
Classes used for communication between TV Kitchen components.

@tvkitchen/base-constants
Constants used for communication between TV Kitchen components.

@tvkitchen/base-errors
Errors used by other base packages.

@tvkitchen/base-interfaces
Interfaces for modular components of the TV Kitchen.
```

#### Relevant Resources / Research
None

#### Related Issues
None

**Comment by reefdog** [comment]
Sure, though let's mention TV Kitchen in the errors package too: `Errors used by TV Kitchen components.`

**Comment by reefdog** [comment]
Oh interesting; it plucked off the first line of the respective READMEs to generate those descriptions! Presumably if I update each project's `package.json` with a `description` field, it'll use those going forward.
