### ISSUE TITLE
Create a PayloadArray type

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#40]
#### Description
As part of the development of our first appliances we're starting to better understand how we want to interact with and store Payloads.

The idea of a PayloadArray class is that it will provide a series of Payload-specific data methods that will be commonly used by Appliances and other parts of the system.

For example:

1. `insertPayload`: would insert a Payload at the appropriate position based on its time metadata.
2. `filterByType`: would return a PayloadArray that only contains payloads of the specified type.
3. `filterByPosition`: would return a subset of the PayloadArray based on the time range specified.

#### Relevant Resources / Research
* [This article on extending native classes](https://javascript.info/extend-natives)

#### Related Issues
* [The appliance discussion over in our appliances repo](https://github.com/tvkitchen/appliances/issues/19)

**Comment by reefdog** [comment]
Small note, I'd say `sliceByTime` or `filterByTime` are both clearer and more consistent with `filterByType` than `sliceTime`. (I get the "slice" terminology is consistent with arrays, but isn't it functionally doing the same thing as `filterByType` but with more complex logic?)

Although I _really_ want it to be `TIMESLICE!!()` all caps and with two exclamation marks.

**Comment by slifty** [comment]
Great point; editing `sliceTime` => `filterByPosition`

**Comment by slifty** [comment]
I was torn on whether this should extend `Array` directly, or if it should just use Array as an underlying data type.

I am leaning towards NOT extending array.  We don't want data inserted outside of `insert` since so much relies on internal integrity of payload order.

Exposing the array via an `array` getter or a `toArray` method would be a good compromise for folks who want to be able to do array-stuff like map and reduce.

... I reserve the right to change approach as I finish implementation!
