### ISSUE TITLE
How come packages don't have yarn.lock files?

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#52]
#### What do you want to talk about?
I notices that `package/interfaces` doesn't have a lockfile despite having a dependency.  Is this expected? Is something wrong?

#### Relevant Resources / Research
None.

**Comment by slifty** [comment]
This is discussed in some detail over https://github.com/yarnpkg/yarn/issues/5428

Short answer is: because lockfiles are for development of packages, not for use of packages!

It sounds like there's a use case that would make package-level lockfiles important (and we may face that in the [Appliances monorepo](https://github.com/tvkitchen/appliances) once we start talking Docker for appliances), but we can cross that bridge if we need to later.

**Comment by reefdog** [comment]
> Short answer is: because lockfiles are for development of packages, not for use of packages!

Wouldn't it be the reverse? For use, not development, of packages?

**Comment by slifty** [comment]
I intended it as written (doesn't mean I'm right; just mean that's what it sounded like when I read the discussion there)

```
When you publish a package that contains a yarn.lock, any user of that library will not be affected by it. When you install dependencies in your application or library, only your own yarn.lock file is respected. Lockfiles within your dependencies will be ignored.

it doesn't seem necessary to bundle yarn.lock when publishing the individual package... it is more a development artifact for the whole repo, therefore, no need to put it in each package.
```

Basically, for folks who are developing packages (cloning the repo) we want everybody using the same version of all the deep down traces of dependencies and not having it shift around every time you yarn install.

For users of the package they already have their own lockfiles to accomplish that.  The version they install should be based on the latest version available at the time that fits the `package.json` requirements, it should NOT be "locked" into the latest version that happened to be available when a given package was published.

**Comment by reefdog** [comment]
Goooot it! 🤦‍♂️ Of course.

**Comment by slifty** [comment]
(I had to think about it a few times to realize what was going on too!)
