### ISSUE TITLE
Silence tests by default

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#53]
#### Description
We test a logger, which of course means logs are written to console during tests.  We should silence logs by default.

#### Relevant Resources / Research
Jest has a `--silent` flag which we should set (it can be offset with `--no-silent` if necessary)

#### Related Issues
None

**Comment by chriszs** [comment]
Should just be able to port my PR.

**Comment by slifty** [comment]
This project doesn't use winston so I *think* the implementation is a bit different (just a literal change to the `package.json` `yarn:test` command)

**Comment by chriszs** [comment]
Oh yes, you'd just need to add `silent: true` to your Jest config.
