### ISSUE TITLE
Update Payload default for createdAt

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#62]
#### Description
Right now we [have some default values assigned for Payload values](https://github.com/tvkitchen/base/blob/a51d1ca9d0be87b56ea9cdff2116be75a52d4706/packages/classes/src/Payload.js#L1-L8); I'm having trouble thinking of a reason why we should not set `createdAt` to the current time if it is not provided on construction.

Otherwise anybody creating a new Payload will always have to specify the createdAt timestamp.

#### Relevant Resources / Research
None.

#### Related Issues
None.

**Comment by Laurian** [comment]
PayloadFactory has the clock :trollface:
