### ISSUE TITLE
Reduce serialization size

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/base#74]
#### Description
One issue I identified while trying to [optimize ingestion performance](https://github.com/tvkitchen/tv-kitchen/issues/77) was the size of serialized payloads.

Here's what I wrote there:

> Tested switching to sending binary data via Kafka just now. It did seem to improve performance, maybe enough that it won't stall. (Though performance seemed to vary a lot for reasons I couldn't fully determine. I want to understand that better.)
> 
> Significantly, though, it sends a lot fewer bytes. I listened to the Kafka output stream with kafka-console-consumer and received 465 JSON serialized messages, which when redirected to a file amounted to 19.2 MB on disk. With binary data, 741 messages took 4.8 MB. That's about 6.4 times smaller. This makes sense when you consider a single byte from a buffer encoded in JSON is typically represented by a two to three digit number and a comma in a Unicode string (e.g. `138,`), or three to four times two bytes.
>
> Here's what I'm doing to test this:
```js
.send({
    topic: dataTypes.STREAM.CONTAINER,
    messages: [{
        value: payload.data,
        headers: {
            type: payload.type,
            position: JSON.stringify(payload.position),
            duration: JSON.stringify(payload.duration),
            createdAt: payload.createdAt,
        }
    }],
})
```

I'm using Kafka headers here for the metadata, so I can give Kafka the data buffer directly. If implemented, this might change the structure of how serialize would be called.

Another option might be to wrap the metadata into a buffer with the binary data and send that. The Kafka native way to do this seems to be to use Avro. Here's how that might look, using the [avsc](https://github.com/mtth/avsc) library:

```js
import avro from "avsc"

const payloadType = avro.Type.forSchema({
  name: 'Payload',
  type: 'record',
  fields: [
    {name: 'type', type: 'string'},
    {name: 'data', type: 'bytes'},
    {name: 'position', type: 'int'},
    {name: 'duration', type: 'int'},
    {name: 'createdAt', type: 'string'},
  ]
});

// ...

serialize(payload) => payloadType.toBuffer(payload)

deserialize(serializedPayload) => payloadType.fromBuffer(serializedPayload)
```
(I prototyped this using RunKit [here](https://runkit.com/embed/z4spxdxbv3c3).)

This seems nifty! And maybe what we should do. There's a whole other layer in Avro around synchronizing schemas across platforms, but it seems like maybe we don't even need to deal with that yet.

I also haven't verified Avro performance claims. Supposedly much faster than JSON serialization, but presumably slower than just giving Kafka the buffer directly.

But I think this boils down in part to whether we think the metadata we're sending should be treated as metadata by Kafka or not and whether we want to change how serialize is used or not.

#### Relevant Resources / Research
- [kafkajs-avro](https://www.npmjs.com/package/kafkajs-avro)- which extends kafkajs to use avro transparently, also may deal with the Avro schema sharing stuff
- [avsc](https://github.com/mtth/avsc) - a lower level library which implements the Avro serialization
- [only partially helpful Google results for "kafka headers"](https://www.google.com/search?q=kafa+headers)

#### Related Issues
tvkitchen/tv-kitchen#77

**Comment by chriszs** [comment]
Actually now that I'm looking at how to integrate this into `Payload`, I wonder you could replace all of it with the return value of `avro.Type.forSchema`, which is a factory that creates objects of type `Payload` and implements defaults, validation and a resilient `isType` check. It's built to be a data transfer object.

**Comment by slifty** [comment]
One thought (I appreciate this is about 4 hours too late!)

We have not written the emitter, but I expect `Payload` to be a type that we're going to want to stream over SocketIO / WebSockets for the emit API. I want to just raise that because I think it would be worth avoiding coupling it with kafka / avro directly in the `base-classes` level.

I'll shift over to the PR and talk more about it there!

**Comment by chriszs** [comment]
Dan and I just talked about this. It's possible we'll want to use the binary Avro format even in some WebSockets, for the same performance/bandwidth reasons we're using it here, but we don't want to depend on it, particularly for client side applications (it's possible to use Avro even there, but it's unknown how much of a pain it would be). Some potential paths forward:

1. Refactor the PR to decorate `Payload` with like a `BinaryPayload` or `AvroPayload` that implements alternate serialization and deserialization.
2. Or do that serialization at the point of sending the message.

In either scenario, we could move the schema to somewhere both `Payload` and the `BinaryPayload` could use, eliminating repetition between them.

**Comment by chriszs** [comment]
I'm also going to take another look at PBF.

**Comment by chriszs** [comment]
Although it remains to be seen how many client-side authors will even bother with an official class of any sort, if they can just do JSON.parse().

**Comment by chriszs** [comment]
Also going to try adding [compression](https://kafka.js.org/docs/producing#compression-snappy) when sending. My guess is this will save a lot more. But that's probably a ticket for the repos that read or send with Kafka.

**Comment by chriszs** [comment]
See also: https://github.com/socketio/socket.io-protocol

**Comment by chriszs** [comment]
Socket.IO has a default parser it includes by default that implements its protocol, but [supports drop-in replacements](https://socket.io/docs/client-api/#With-a-custom-parser), including a pre-made one for MessagePack.
