### ISSUE TITLE
Should this actually be a monorepo

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#9]
#### What do you want to talk about?

By creating a monorepo we can have different subcomponents as their own package.  For instance then it would be possible to have code that uses the package do things like:

```
import { NotImplementedError } from '@tvkitchen/base-errors'
```

instead of

```
import { errors } from '@tvkitchen/base'
const { NotImplementedError } = errors
```

This isn't a huge rabbit hole to go down in the immediate term, but something we should read up on this month.

#### Relevant Resources / Research
https://doppelmutzi.github.io/monorepo-lerna-yarn-workspaces/

**Comment by slifty** [comment]
Note: since we're using yarn I believe this would be as simple as creating a `projects` directory, adding a `workspaces` field to our package.json, and creating `package.json` files for each project we want to export.

I imagine it would be a 30 minute change, so worth deciding on now.

The bigger question is whether the *entire* tv kitchen should be a monorepo... definitely want to punt on that for now.

**Comment by slifty** [comment]
As for this repo: yes we want it to be done using [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/).  I'll take that on and open a PR.  From there we'll be able to actually start building things with this stuff!

**Comment by slifty** [comment]
We may want to use Lerna too in order to have common build / test processes across the packages [here's a guide](https://medium.com/hy-vee-engineering/creating-a-monorepo-with-lerna-yarn-workspaces-cf163908965d).

**Comment by slifty** [comment]
Today I Learned that `.babelrc` is not the recommended way to configure babel, but [`babel.config.json` is](https://babeljs.io/docs/en/configuration).

What's more, `.babelrc` doesn't work in monorepos.

**Comment by Laurian** [comment]
Citation needed
